apiVersion: v2
name: kubeflow
description: >
  A Helm chart that generates ArgoCD AppProject and Application resources for Kubeflow components,
  preconfigured according to the upstream examples/kustomization.yaml structure.

type: application
version: 1.1.0
appVersion: "1.11.0"

home: https://github.com/vitu-mafeni/kubeflow-gitops
maintainers:
  - name: VitumbikoMafeni
    email: vitumafeni@dcn.ssu.ac.kr
sources:
  - https://github.com/vitu-mafeni/kubeflow-gitops
keywords:
  - kubeflow
  - argocd
  - helm
  - gitops
  - machine-learning
  - fluxcd
  - ml-platform